name: wikiberria
description: "A catalog of berries"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/fonts/AppIcon.ttf
  assets:
    - assets/icons/
    - assets/images/berries/
    - assets/data/berries_catalog.json
